
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<?php 
     $specialprice = $_product->getSpecialPrice(); 
    // Get the Special Price FROM date
    $specialPriceFromDate = $_product->getSpecialFromDate();
    // Get the Special Price TO date
    $specialPriceToDate = $_product->getSpecialToDate();
    // Get Current date
    $magentotoday =  Mage::getModel('core/date')->date('Y-m-d H:i:s'); //time();
  
$magentotoday = date('Y-m-d H:i:s',strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true)));

    if (($specialprice != null || $specialprice != '') && $specialPriceToDate!=NULL):
 
    if((strtotime($magentotoday) >= strtotime( $specialPriceFromDate) && strtotime($magentotoday) <= strtotime($specialPriceToDate.'+1 days')) ):
?>
<div class="countdown-block">
  <h5><?php echo Mage::getStoreConfig('pricecountdown/price_countdown_config/header_content'); ?></h5>
  <div id="clockdiv">
    <div>
      <span class="days"></span>
      <div class="smalltext">D</div>
    </div>
    <div>
      <span class="hours"></span>
      <div class="smalltext">H</div>
    </div>
    <div>
      <span class="minutes"></span>
      <div class="smalltext">M</div>
    </div>
    <div>
      <span class="seconds"></span>
      <div class="smalltext">S</div>
    </div>
  </div>
</div>
<?php  
	$s = explode('-', $specialPriceToDate);
	$specialPriceToDate = str_replace('-', '/', $specialPriceToDate);
	//$magentotimezone = Mage::getStoreConfig('general/locale/timezone');
	
?>
 
<script type="text/javascript">
      var start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
    var  current = start;
     var current = new Date(current);
/*		var currentDecremented = new Date(current);
		currentDecremented.setSeconds( current.getSeconds() - 1 ); */

	
function getTimeRemaining(endtime) {
	current.setSeconds( current.getSeconds() + 1 );
  var t = Date.parse(endtime) - Date.parse(current);		//alert('t : ' + t);
  var seconds = Math.floor((t / 1000) % 60);
  var minutes = Math.floor((t / 1000 / 60) % 60);
  var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
  var days = Math.floor(t / (1000 * 60 * 60 * 24));
  return {
    'total': t,
    'days': days,
    'hours': hours,
    'minutes': minutes,
    'seconds': seconds
  };
}

function initializeClock(id, endtime) {
  var clock = document.getElementById(id);
  var daysSpan = clock.querySelector('.days');
  var hoursSpan = clock.querySelector('.hours');
  var minutesSpan = clock.querySelector('.minutes');
  var secondsSpan = clock.querySelector('.seconds');

  function updateClock() {
    var t = getTimeRemaining(endtime);

    daysSpan.innerHTML = t.days;
    hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
    minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
    secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);

    if (t.total <= 0) {
      clearInterval(timeinterval);
    }
  }

  updateClock();
  var timeinterval = setInterval(updateClock, 1000);
}


 //var deadline = new Date(Date.parse("<?php //echo Date('F j, Y',strtotime($specialPriceToDate)); ?>"));
 var deadline = new Date("<?php echo Date("m/d/y h:i:s A", strtotime($specialPriceToDate)); ?>");
 var deadlineadded = new Date(deadline);
 deadlineadded.setSeconds( deadline.getSeconds() + 86399 ); // (24 * 60 * 60) - 1 = 86399
initializeClock('clockdiv', deadlineadded);
</script>


   <?php  
        endif;
    endif;
?>


<ul class="add-to-links">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
<?php endif; ?>
<?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>
<?php if($_compareUrl) : ?>
    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
<?php endif; ?>
</ul>

